### ISSUE TITLE
Gulp > Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by mashcode** [yeoman/generator-mobile#77]
Gulp > Error: Cannot find module 'postcss'
...
schmendrick:site marc$ gulp
[16:11:09] Using gulpfile ~/Sites/NYCompost/site/gulpfile.js
[16:11:09] Starting 'clean'...
[16:11:09] Finished 'clean' after 12 ms
[16:11:09] Starting 'default'...
[16:11:09] Starting 'styles'...
[16:11:14] 'styles' errored after 4.49 s
[16:11:14] Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/marc/Sites/NYCompost/site/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:6:13)
    at Object.<anonymous> (/Users/marc/Sites/NYCompost/site/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:111:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
[16:11:14] 'default' errored after 4.5 s
[16:11:14] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/marc/Sites/NYCompost/site/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/marc/Sites/NYCompost/site/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/marc/Sites/NYCompost/site/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/marc/Sites/NYCompost/site/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/marc/Sites/NYCompost/site/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/marc/Sites/NYCompost/site/node_modules/run-sequence/index.js:45:4)
    at Gulp.emit (events.js:129:20)
[16:11:15] gulp-ruby-sass: directory
[16:11:18] gulp-ruby-sass: write components.css
      write components.css.map
[16:11:22] gulp-ruby-sass: write main.css
      write main.css.map

**Comment by crhym3** [comment]
I believe it might be because of your other issue #76.

**Comment by crhym3** [comment]
Hey @mashcode did you manage to get it working?

**Comment by mashcode** [comment]
> On Feb 20, 2015, at 11:46 AM, alex <notifications@github.com> wrote:
> 
> Hey @mashcode did you manage to get it working?
> 

I wish. I'm using the generator to scaffold three to four small Jekyll projects. The good news? I'll be knee deep and fix it

**Comment by arthurvr** [comment]
This does look like an all-day npm installation issue isn't it? Try re-running `npm install` yourself, does that result in anything?

**Comment by kevva** [comment]
Yes, this is just a broken `npm install`, try running it again.

**Comment by Anujmoglix** [comment]
I tried to run it but facing same issue in ionic serve 

> Error: Cannot find module 'postcss'
